### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by barbalex** [ibrierley/flutter_map_line_editor#13]
So far I have only installed. Successfully. I had to remove flutter_map_dragmarker though because of:

```
[capturing] flutter pub get
Running "flutter pub get" in capturing...                       
Because every version of flutter_map_line_editor from git depends on flutter_map_dragmarker from git {url: https://github.com/ibrierley/flutter_map_dragmarker.git, ref: nullsafety, path: .} and capturing depends on flutter_map_dragmarker from git {url: https://github.com/ibrierley/flutter_map_dragmarker, ref: nullsafety, path: .}, flutter_map_line_editor from git is forbidden.

So, because capturing depends on flutter_map_line_editor from git, version solving failed.
pub get failed (1; So, because capturing depends on flutter_map_line_editor from git, version solving failed.)
exit code 1
```

But that will be fine once flutter_map_dragmarker is updated.

**Comment by ibrierley** [comment]
Thanks for testing, curious I don't get any errors (maybe as I'm running locally, but I do have the same pubspec...are you running the examples or your own test?). If you get bored sometime and want to paste the output of flutter pub deps, I'd be interested, but I suspect it won't be long before I move it to master anyway

**Comment by barbalex** [comment]
The reason I get it is: I am testing it in my app. I first tested flutter_map_dragmarker, so I added it to pubspec. Then to test flutter_map_line_editor I added that too. That configuration caused this error message. You probably have not done it this way, so you did not run into it.
```yaml
  # uncommented flutter_map_dragmarker as included in flutter_map_line_editor
  # and flutter does not like a git source being imported twice
  #flutter_map_dragmarker:
  #  git:
  #    url: https://github.com/ibrierley/flutter_map_dragmarker
  #    ref: nullsafety
  flutter_map_line_editor:
    git:
      url: https://github.com/ibrierley/flutter_map_line_editor
      ref: nullsafety
```
Sorry for not being clear enough.
